### ISSUE TITLE
Feature request: Duplicate published observations

### ISSUE THREAD

**Issue by SEilertsen** [nikobojs/manuscrape_electron#20]
It would be nice if there was a way to access and edit the observations after saving them - just in case you find a mistake afterwards. This could be that the owner of the project approves it or that the owner can select whether or not to lock the observations.

**Comment by nikobojs** [comment]
I see the need. But the locking-feature might be important for data integrity in many research projects. Making it "softer" is probably not in their interest.

A compromise could be adding a "duplicate observation" function, that takes a locked observation and copies it into a draft. And also making it possible for all users to delete _their own_ observations. Would that solve the situation you think?

**Comment by nikobojs** [comment]
Project owners can remove other collaborators' observations now. I think this issue can be solved by adding a duplicate function to observations. Will update the issue title

Edit: original title was "Edit observations after saving"

**Comment by nikobojs** [comment]
It is now possible to unlock observations if enabled in the project settings. If the need for duplicating observations is still preset, please create another issue :+1:
