### ISSUE TITLE
Image editor: Not possible to scroll all the way down

### ISSUE THREAD

**Issue by SEilertsen** [nikobojs/manuscrape_electron#22]
When having a longer image in the image editor, it is often not possible to scroll all the way to the bottom of the image. This results in having to "drag" the picture down instead.

**Comment by nikobojs** [comment]
Thanks for issue! Not sure if I understand this correctly. But if I upload a very high portrait mode picture, i should be able to reproduce your experience if i am looking for the bottom of the picture. Right?

**Comment by nikobojs** [comment]
I cannot reproduce the error. Will close the issue due to inactivity. The bug is probably already fixed.
