### ISSUE TITLE
Image editor: toolbar stays in the top when scrolling

### ISSUE THREAD

**Issue by SEilertsen** [nikobojs/manuscrape_electron#24]
It would be very helpful if the toolbar with the zoom option, the option to choose the figures and change colors would follow along when scrolling down in the image editor. When working in longer images, it takes quite a while to scroll up and down in order to write text or change color.

**Comment by nikobojs** [comment]
Thanks. You are not the first to request that exact feature. This is definitely something that should be fixed somehow.

**Comment by nikobojs** [comment]
Fixed in https://github.com/nikobojs/manuscrape_nuxt/pull/6
