### ISSUE TITLE
Parameter option "Dropdown or text" does not work

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#25]
Can't choose open text field when using the function and get error message "drop down field type 'AUTOCOMPLETE_ADD' is not supported"

![billede](https://github.com/nikobojs/manuscrape_electron/assets/148208085/a9b0c445-7556-424e-809d-7c01cb4e992a)

**Comment by nikobojs** [comment]
Thanks. This problem is fixed and will be released later today :-)

**Comment by nikobojs** [comment]
Fixed and released to manuscrape.org :ok_hand:
