### ISSUE TITLE
Image editor: textbox - changing the size of the box

### ISSUE THREAD

**Issue by SEilertsen** [nikobojs/manuscrape_electron#26]
It would be nice to be able to change the size and shape of the textboxes so they can also be rectangular. Preferably then the size of the box would not change unless you dragged it manually.

**Comment by nikobojs** [comment]
Aha interesting! What if you write text thats wider than the box, or you write multiple lines, exceeding the height of the box? Should the box expand?

**Comment by nikobojs** [comment]
Related: https://github.com/nikobojs/manuscrape_electron/issues/18

**Comment by nikobojs** [comment]
Now you draw the box before you write. I hope this improves the experience - if not, please create another issue. Closing
