### ISSUE TITLE
Image editor: text box - size of the text field editor

### ISSUE THREAD

**Issue by SEilertsen** [nikobojs/manuscrape_electron#27]
It would be nice to have the option to make the text field editor larger for when writing the text for the text boxes. It becomes a bit difficult to see the whole text when writing longer notes.

**Comment by nikobojs** [comment]
Right now, the text area is placed on top of the image. So larger textarea means less image visible. I think it makes sense to move many tools around, but I am not entirely sure how. I'd like to hear a designer's thoughts on this.

For now, this issue can be fixed my making the textarea resizeable and slightly bigger.

**Comment by nikobojs** [comment]
This is solved now as you type directly on the picture.
