### ISSUE TITLE
Image editor: choosing different colors

### ISSUE THREAD

**Issue by SEilertsen** [nikobojs/manuscrape_electron#28]
For the lines and boxes without text I am a bit unsure what the second "pencil" is for. When making the lines, I can choose a different color for the pencil on the right, but only the one on the left actually changes the color of the line. For the boxes without text this is the opposite - the pencil on the right changes the color of the box, but the pencil on the left doesn't do much.

**Comment by nikobojs** [comment]
Yes. I made a UX test yesterday and the unused pencil-buttons surely are confusing. We could hide the unused pencil, i think that is the most easy fix for now.

**Comment by nikobojs** [comment]
Fixed in https://github.com/nikobojs/manuscrape_nuxt/pull/6
