### ISSUE TITLE
Feature request: Delete uploaded files

### ISSUE THREAD

**Issue by SEilertsen** [nikobojs/manuscrape_electron#31]
As far as I can tell it is not possible to delete the videos after capturing them. I tried opening the video and clicking "edit" -> "delete" but this did not work

**Comment by SEilertsen** [comment]
I am not sure if this is the case for uploaded files and images as well

**Comment by nikobojs** [comment]
Yes. The issue original title was "Video captures: deleting captured videos" - just renamed it because right now no files can be deleted, and that's of course a problem :-) Will fix it within a couple of weeks, hopefully within this week.
