### ISSUE TITLE
Suggestion: Fit text size to window

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#39]
When creating a text-box by holding left mouse-button down and dragging, make the text size fit the size of the box instead of changing the box size to what ever size the text size was set to.

**Comment by nikobojs** [comment]
Ahhaaa! I've tried to hack this UX so hard... Thank you :sweat_smile:  :rocket: will refactor the textbox fontsize fix in https://github.com/nikobojs/manuscrape_nuxt/pull/6 and release within 2 days.
