### ISSUE TITLE
On manuscrape.org: Sort by- functions only sort the current page, not all observations across pages

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#46]

**Comment by nikobojs** [comment]
Just to clarify - when you change page in the observation list, the current sort-by-column setup gets reset?

**Comment by Pedrotheplant** [comment]
Something like that. So when I e.g., click "sort by date", it only sorts the six observations on page 1, whereas it should sort all observations across pages, but the observations seem to remain within "their page", so no observations move across pages when sorting.

**Comment by nikobojs** [comment]
Sorting as an isolated issue is fixed now. However, if you pick an observation filter, they pages are still weird (open issue: #47 ).

Will close this :+1:
