### ISSUE TITLE
Different amount of observations show up on the observations-window

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#47]
When clicking through the different pages in the observation window, it shows different amounts of observation per page. Some pages show six observations, some show three, etc

**Comment by nikobojs** [comment]
This is partially fixed now. If you choose the filter "Show all my drafts" there should be no problem and sorting should be fixed across pages as well :-) Will keep the issue open until the draft filtering works between pages

**Comment by nikobojs** [comment]
I finally fixed this issue :sweat_smile:  Will deploy to manuscrape.org later today

**Comment by nikobojs** [comment]
Its live now
