### ISSUE TITLE
Exported excel sheet does not maintain line breaks from multi-line text fields

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#48]
If this is not feasible to code atm, can we make it so that the line breaks get represented as " / " (space slash space)?

**Comment by nikobojs** [comment]
It works on LibreOffice on Fedora, but might be because of the newline characters (\r\n vs \n). I have replaced all newline characters with \r\n for windows optimization. Don't know if it'll fix it but try it out!

**Comment by Pedrotheplant** [comment]
Problem solved! For this to work you need to enable "wrap text"!
