### ISSUE TITLE
Request: option to have multible selectable in dropdown menu or from list of labels.

### ISSUE THREAD

**Issue by Mod-lab-stoff** [nikobojs/manuscrape_electron#51]
Would be nice to have an option that makes it possible to select more than one item on a dropdown menu or create a group of checkable boxes.

**Comment by nikobojs** [comment]
Nice. It makes good sense

The UI library has a nice dropdown with multiple select options (The "Async Search" example): https://ui.nuxt.com/forms/select-menu#async-search

Could this be the form component for the project parameter type?

**Comment by Mod-lab-stoff** [comment]
Yes that would be cool!
Is it possible to add a freetext or misc option to the multiple select option too? So you might have 5 known outcomes and one for miscellaneous

**Comment by nikobojs** [comment]
Ah, so do you mean like the "Create option" example? [https://ui.nuxt.com/forms/select-menu#create-option](https://ui.nuxt.com/forms/select-menu#create-option)

Dont mind the "Search..." placeholder - you can create new options just by typing.

What should the name of the type be? :sweat_smile: "Multiple choice dropdown with custom options"

**Comment by Mod-lab-stoff** [comment]
Yes that works well!
Thats a good name. Or maybe "multible choice or free text" to shorten it.

**Comment by nikobojs** [comment]
It's done and will be released tomorrow! :smile:
