### ISSUE TITLE
When taking a screenshot the grey overlay is also recorded.

### ISSUE THREAD

**Issue by Mod-lab-stoff** [nikobojs/manuscrape_electron#52]
When screenshotting, and not when scrollshotting, the picture has a gray tint much like the overlay, that fills the active monitor when taking screenshot snippets.

**Comment by nikobojs** [comment]
Oh no, that sounds critical... Do you think it could actually be the overlay? Will try to reproduce, fix and release today.

**Comment by Mod-lab-stoff** [comment]
yes it looks like it.
Here is an example from onenote with a white background

new image link:
![image](https://github.com/nikobojs/manuscrape_electron/assets/149067130/4813846f-8ace-4161-a6ed-824f43f94bc8)

**Comment by nikobojs** [comment]
[this commit](https://github.com/nikobojs/manuscrape_electron/commit/17fb0383a6d3ded961a02a918fdad2d67c3d813a) will ensure the background overlay is not drawn after drag release.

[this commit](https://github.com/nikobojs/manuscrape_nuxt/commit/6fe78812bc2c594524dccb02282a9d5655929454) will remove opacity from the thumbnail in the observation window. Not sure if it looks better, but it makes more sense anyway.

**Comment by nikobojs** [comment]
Please verify if v1.0.4 (requires reinstall) fixes the problem

**Comment by Mod-lab-stoff** [comment]
Hey Niko i installed v1.0.4, Now when i take a screenshot i get this message instead.
![image](https://github.com/nikobojs/manuscrape_electron/assets/149067130/e7e9a359-4875-4409-997b-5a28a1d22677)


Also noticed, that when i take a screenshot from the top pixel it drags the edge of the overlap down instead. Don't know if its a bug or a feature.

**Comment by nikobojs** [comment]
Interesting. Not getting this error myself, but I have changed the line according to the error msg. Can you test again? :pray: (no need to reinstall)

**Comment by Mod-lab-stoff** [comment]
It works now and the color is fixed!

thanks!
