### ISSUE TITLE
Export videos as mpeg4 or similar format?

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#58]
The current .webm format does not work in Nvivo.

**Comment by nikobojs** [comment]
Damn NVivo :disappointed:

Then there needs to be an automated conversion step, as [the used method](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API) used only supports webm. This is totally possible and not a giant task. But I am thinking this whole video capture feature should completely rethought, as there are many problems with this exact feature.

Related: https://github.com/nikobojs/manuscrape_electron/issues/7

**Comment by nikobojs** [comment]
Closing because the video feature is removed for now.
