### ISSUE TITLE
Make UI for parameter fields longer horizontally

### ISSUE THREAD

**Issue by Mod-lab-stoff** [nikobojs/manuscrape_electron#63]
Hi

Would it be possible to make the boxes for eg drop down menus longer in order to display more text? Or maybe make it scale with the window. If you have long descriptions of observations, you can't see the full description

![image](https://github.com/nikobojs/manuscrape_electron/assets/149067130/247ab72a-314a-49b2-98bf-e50cf447ad95)

**Comment by Mod-lab-stoff** [comment]
I just noticed that it expands to the option you choose. Maybe it can just automatically expand to the largest option?

**Comment by nikobojs** [comment]
It's a deep rabbit hole to determine lengths of the text of all options.
Instead I added minimum length of 200px on all dropdowns, so hopefully this should fix the issue for you. I'll close this issue for now, please create a new if its still a problem. Will release the fix today
