### ISSUE TITLE
24-hour clock option

### ISSUE THREAD

**Issue by Mod-lab-stoff** [nikobojs/manuscrape_electron#64]
Hi

would it be possible to get a 24-h clock option for date/time?
![image](https://github.com/nikobojs/manuscrape_electron/assets/149067130/836a96a8-6d22-4d07-862f-cd237c04e01e)

**Comment by nikobojs** [comment]
related: https://github.com/nikobojs/manuscrape_electron/issues/8
Seems the whole datepicker (and datetime picker) needs to be refactored completely

**Comment by nikobojs** [comment]
Closing issue due to duplication: https://github.com/nikobojs/manuscrape_electron/issues/8
