### ISSUE TITLE
Export: add option to export specific observation or range of observations

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#66]

**Comment by nikobojs** [comment]
The range, like "all the observations created between date A and date B" ? Or another kind of range?

**Comment by Pedrotheplant** [comment]
I'm not an UI/UX expert, so let me hear what you think:

Adding a checkbox next to each observation so you can select observations from the menu and then click "export selected observations". Then if users want to export by date-range they can sort the observations accordingly, mark the right observations and then click "export selected observations". Adding to this, we could have an option in the sorting-bar called "select all visible observations".

**Comment by nikobojs** [comment]
Ah yes, that makes sense.

To solve this issue while enabling as many use cases as possible, my proposal is:

1. When you click any export button, an export-settings dialog window opens
2. In the dialog, you get to choose between 3 basic observation filters (all, all in date-range and "cherry-picked")
3. If you choose cherry-picking, an observation table shows with checkboxes as you describe

With this solution we can easily add more export settings later.

How does that sound?

**Comment by Pedrotheplant** [comment]
Sounds great!

**Comment by samuelhimmelstrup** [comment]
Assign me to this one, I will do it along with the "keep export log" one. Hopefully I will have time this week, if not then next! :-)

**Comment by nikobojs** [comment]
This feature is done with the exception of cherry picking. And released. @Pedrotheplant I would appreciate if you could test what there is now, and see if cherry picking or other features are still needed. Will close this issue (almost a year old :sweat_smile: ) - please open a new one if needed :+1:
