### ISSUE TITLE
Keep export-log

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#71]
It would be nice to have an export log, so one can see when the last time one exported the observations, thus avoiding dublettes.

**Comment by nikobojs** [comment]
There is also a feature request (https://github.com/nikobojs/manuscrape_electron/issues/66) that includes a variety of ways to export using date ranges.

If we combine this with information about "when who exported what", it should solve the confusion i think. Interesting proposal !

**Comment by samuelhimmelstrup** [comment]
I will look into this. Not sure if I can assign myself to this issue, maybe it is only @nikobojs who has permission to assign?

**Comment by samuelhimmelstrup** [comment]
Okay @Pedrotheplant, I need a bit of additional info before I can do this:

1) Do you need to see all exports that have been made by all contributors for a project, or just your own exports?
2) With new options for exporting, how much info do you need to see? 

It would be very nice if you could show me the view you have in mind. Like for example:

**Exports:**
Team Member B: _All observations before 17/02/2024_
You: _From: 03/07/2023 To: 22/01/2024_ 
You:  _Cherrypicked_ (With option to click for more info)

or only your own and with date ranges for the "All observations" option:

**Your Exports:**
- _From: 01/03/2023 To: 28/04/2024_  (with 01/03/2023 being the date of the first observation)
- _From: 03/07/2023 To: 22/01/2024_ 

Many ways to do it, so I would appreciate some more feedback on what would be the most useful :-)
Cheers Samuel

**Comment by Pedrotheplant** [comment]
Hi Samuel! Awesome that you're looking into it!

1: I think the project owner needs to be able to see all exports by all contributors. Once the feature of letting other contributors export (#87), we could perhaps add a conditioned drop down, saying "let contributor access export logs of: their own exports only <--> all project members' exports", if the contributor is allowed to export.

![manuscrape export](https://github.com/nikobojs/manuscrape_electron/assets/148208085/57b7e6d1-9690-44cd-9b9e-c67e88cbebf9)



2: It would be nice to see whatever is needed to replicate the export. So basically the export date, the user and the export parameters. So:

**Export log**
- 29-04-2024: 
--> User A: _All observations before 29-04-2024_
--> User B: _All observations from: 01-03-2024 to: 31-03-2024_

- 27-04-2024:
--> User C: _Observations from: 15-02-2024 to: 29-04-2024 with the following attributes [XX; YY; ZZ]_

Does it make sense? :)

**Comment by samuelhimmelstrup** [comment]
1) alright, project owner can see everybody exports. What about other members, can they see everybodys exports or just their own?

2) just to be sure, can you specify what is meant by "attributes". The cherry picked option is the most complicated to implement, so I want to be sure what is needed. Is it "check off any number and combination of observations" or "all observations (in date range) that has a special characteristic. Hope my question makes sense 🙂

**Comment by Pedrotheplant** [comment]
1. Can we make that a toggle for the other members? So as a default they can only see their own exports, and then "see all exports" can be toggled?

2. I'm not entirely sure how to read your examples, so let me know if my answer doesn't make sense :) If I read @nikobojs suggestion in #66 correctly, then it's the first of your two examples :) 

I had forgotten about his suggestion in #66 , when I wrote the previous comment, my apologies! I think the parameterbased one (your second example) is probably best left for subsequent data analysis outside of manuscrape :)

**Comment by nikobojs** [comment]
I believe this issue can be closed after the latest release (https://github.com/nikobojs/manuscrape_nuxt/releases/tag/1.1.0)

If other exports features are needed, please open a new issue :+1:
