### ISSUE TITLE
enable administrative reopening of observations

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#73]
Is it possible to let project-owners reopen observations, so that the collaborator can e.g., add a file? Have had a few situations now where a collaborator pressed "submit" too early.

**Comment by nikobojs** [comment]
Next release will contain project-settings for the permission to "unlock" observations. It will be possible by the project owner and/or the project author, depending on the project settings. The project settings will be public for all collaborators and editable for project owners.

I think this creates the feature you're asking for, including in any other situations where observations needs editing after publishing.

**Comment by nikobojs** [comment]
Released in v1.0.6. If issue persists, please create another issue :+1:
