### ISSUE TITLE
Ability to rearrange parameters

### ISSUE THREAD

**Issue by stoffaa** [nikobojs/manuscrape_electron#75]
Last parameter you add goes to the bottom of the list it seems.
I would like to rearrange order to better fit workflow.
![image](https://github.com/nikobojs/manuscrape_electron/assets/98823305/d3122bce-06db-4016-b59d-03a1fedeeb7c)
In this case i want avatar to be the first.
Could we get a drag and drop rearrangement or something?

**Comment by samuelhimmelstrup** [comment]
I will take a look into this issue :-)

**Comment by nikobojs** [comment]
@samuelhimmelstrup I have already done some refactoring on my branch. Will make a PR soon

![Screenshot from 2024-03-15 14-42-23](https://github.com/nikobojs/manuscrape_electron/assets/22896724/35151f17-0573-4d6e-9819-282f175db06d)

**Comment by nikobojs** [comment]
The dropdown created in https://github.com/nikobojs/manuscrape_nuxt/pull/24 could have "move up" and "move down" options

**Comment by nikobojs** [comment]
![Screenshot from 2024-05-04 13-40-43](https://github.com/nikobojs/manuscrape_electron/assets/22896724/53cbfbee-a441-4c80-abb9-7000ef597350)

Fixed in https://github.com/nikobojs/manuscrape_nuxt/commit/7afcbf988057128e73735de9a381e46c0b57499f

Closing
