### ISSUE TITLE
Unable to write in the text boxes

### ISSUE THREAD

**Issue by tvg112** [nikobojs/manuscrape_electron#92]
While creating a draft, I was trying to edit a photo when I suddenly couldn’t write in the text box of the photo editor. The same issue occurred in the observation parameters section, where I couldn’t write anything either afterwards. Solution was to open and close the app.

**Comment by nikobojs** [comment]
Thanks for your issue. Is there a certain order of actions that will lead to the problem ?

**Comment by JakobDemant** [comment]
@tvg112 Let us shortly discuss the issue today so you could qualify it for @nikobojs

**Comment by tvg112** [comment]
@nikobojs Works fine now! It seems to have been an issue with my computer, as this problem hasn’t occurred since
