### ISSUE TITLE
Cannot delete or rename parameter after project is created

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#96]
User receives error code when trying to delete or rename parameter. When deleting, Manuscrape responds with an error message saying that the parameter does not contain any data.

**Comment by nikobojs** [comment]
Thanks for the issue. I have seen errors that looks like this in the automatic bug reporter. Will take a look at it tomorrow, hopefully.

**Comment by nikobojs** [comment]
This issue should be fixed and deployed 5 mins ago. However it doesn't look like we have a renaming feature yet, as you mention.

Give it a shot and tell me if it works now :pray: 

There was also a bug when creating new project fields. That should work now as well.

**Comment by Pedrotheplant** [comment]
It works!
